export const theme = {
  fontFamily: {
    LexendDeca: `'Lexend Deca', sans-serif`,
  },
  fontSize: {
    mini: '14px',
    default: '16px',
    main: '18px',
    artistTitle: '24px',
    subTitle: '32px',
    title: '64px',
  },
  fontWeight: {
    bold: '700',
  },
  lineHeight: {
    mini: '17px',
    default: '20px',
    main: '22px',
    artCard: '28px',
    subTitle: '40px',
    title: '80px',
  },
  sizes: {
    line: '2px',
    marginMini: '8px',
    marginDefault: '16px',
    margin2x: '32px',
    margin4x: '64px',
    contentPadding: '0 15px',
    artDescriptionPadding: '17px 24px',
    artDescriptionHeight: '132px',
    artDescriptionWidth: '219px',
    artCardWidth: '387px',
    artCardHeight: '444px',
    iconSize: '59px',
    iconMiniSize: '30px',
    burgerSize: '40px',
    burgerLine: '3px',
    navBlockSize: '200px',
    navWidth: '140px',
    artListGapDefault: '25px',
    artListGapMax: '85px',
    artListPaddings: '40px 0 24px',
    heroWidth: '700px',
    heroMargins: '120px 0 72px',
  },
  colors: {
    bodyBackground: '#FAFAFA',
    background: '#FFFFFF',
    text: '#393939',
    whiteText: '#FFFFFF',
    mainAccent: '#F17900',
    secondAccent: '#E0A449',
    headerBackground:
      'linear-gradient(270deg, #343333 13%, #484848 44%, #282828 74%)',
    border: '#F0F1F1',
    searchBackground: '#3939390D',
    favoriteMark: '#F9F9F9',
    favoriteMarkActive: '#FBD7B24D',
  },
  media: {
    tablet: '768px',
  },
};

// export type ITheme = typeof theme;
